
version: "3.3"
services: 
  test-app-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: c4r4mb0l4
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456qwe
  django-app:
    build: .  
    expose:
      - "8080"    
    volumes:
      - type: volume
        source: mystatic
        target: /usr/src/static
        volume:
          nocopy: true
    depends_on:
       - test-app-mysql
    command: bash -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input"
  front:
    image: nginx:1.7.9
    expose:
       - "80"
    depends_on:
       - django-app
    volumes:
      - type: volume
        source: mystatic
        target: /usr/src/static
        volume:
          nocopy: true
      - type: bind
        source: ./http-nginx
        target: /etc/nginx/conf.d    
volumes:
   mystatic: