front:
  image: nginx:1.7.9
  ports:
      - "80:80"
  links:
      - app:app
  volumes:
    - http-nginx:/etc/nginx/conf.d
    - root:/usr/src/static
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: c4r4mb0l4
    MYSQL_DATABASE: mydb
    MYSQL_USER: dmyuser
    MYSQL_PASSWORD: c4r4mb0l4
app:
  build: .  
  links:
    - db:db