apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: test-app
    tier: nginx
spec:  
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: test-app
    tier: nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: test-app
  annotations:
    volume.beta.kubernetes.io/storage-class: "manual"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---      
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
        tier: nginx
    spec:
      volumes:      
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-pv-claim   
      containers:
      - name: nginx
        image: nginx:1.7.9        
        ports:        
        - containerPort: 8000        
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        - name: nginx-persistent-storage
          mountPath: /usr/src/app
