kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-web
  labels:
    type: local
    app: test-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
  labels:
    app: test-app
  annotations:
    volume.beta.kubernetes.io/storage-class: "manual"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi    