#!/bin/bash


mysql_ready() {
        mysqladmin ping --host=test-app-mysql --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1
    }

while !(mysql_ready)
do
   sleep 3
   echo "waiting for mysql ..."
done

python manage.py makemigrations app --no-input
python manage.py migrate app --no-input 
python manage.py collectstatic --no-input
python manage.py initadmin
python manage.py runserver $(ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 172.):8080
#uwsgi --ini conf.ini